### ISSUE TITLE
Add suggested defaults for site to config

### ISSUE THREAD

**Issue by jimmygle** [jimmygle/Homesteader#18]
to should default to something like /home/vagrant/[domain]

```
sites:
    -
        map: homestead.app
        to: /home/vagrant/Code/Laravel/public
```
